# Generated by Django 4.1.2 on 2022-10-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventPage', '0002_remove_eventmodel_is_liked_liked_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked_event',
            name='event',
            field=models.CharField(max_length=20),
        ),
    ]
