# Generated by Django 4.1.2 on 2022-10-23 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EventPage', '0003_alter_liked_event_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked_event',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
